application: freedom-torch-2016
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
